# Lab 2: Pandas
**Author:** Aldo Nunez
**Date:** 2026-04-06

___

#### Topic Outline:

- Data frame basics:
    - Creating data frames.
    - Data frame indexing and attributes.
    - Adding, removing and renaming variables.
    - Slicing (selecting rows/columns).
    - Filtering (selection via logical conditions).
    - Data frame Computations
    - Aggregation and Grouping

**Note:** The `pandas` interface is notoriously confusing and the documentation is inconsistent.  Please be prepared to search through the documentation, research methods for yourself, and experiment with application.  

---

#### Collaboration

You are encouraged to collaborate with other students in your labs, but you are expected to write up your own work for submission.  Please do not copy and paste other people's solutions to problems as it is considered plagiarism and you will be penalized and reported.  Should you choose to collaborate with others, please note their names here:

**Aldo Nunez:** 

**Collaborators:**

1.

___

#### Agent Usage

Additionally, you are permitted to use resources such as ChatGPT and Claude to help you with your lab assignments and to enhance your learning experience.  Please make a note of any agents you have used in this submission here:

**Agents:** 

Gemini

## Introduction

In this lab we will be manipulating `pandas` data frames and preparing messy datasets for analysis.  For this notebook you will need the following libraries:

In [243]:
import numpy as np
import pandas as pd

If you met with the `ModuleNotFoundError` you will need to use your python package manager `pip` (or `pip3`) in the terminal to install the package (see code example below).  Please ask your TA if you are having problems.

pip install pandas

## Pandas

A **data frame** is a tabular data structure with the following properties:

- Each column contains only one data type.
- Columns are indexed (typically string labels).
- Rows are indexed (typically ordinal numbers).

An index is represented by a series object, which is a 1D labelled array.

### Creating Data Frames

The `pandas` documentation provides two primary syntaxes for constructing a data frame from scratch:

1. From a **dictionary**.
2. From row-wise tuples.

#### Data Frames from Dictionaries

We can create a data frame by first creating a dictionary (a concatenation of named lists) using braces.  Here the key values will become the column names and we note that we must ensure that all of the dictionary lists are all of the same length:

In [244]:
# Create a dictionary of athlete information
athlete_dict = {
    'name': ['John', 'Jane', 'Jim', 'Jill'],
    'age': [20, 21, 22, 23],
    'height': [180, 170, 185, 175],
    'weight': [70, 65, 80, 75],
    'team': ['A', 'B', 'A', 'B']
}

We can then use the `DataFrame` function to convert this dictionary into a data frame object:

In [245]:
athlete_df = pd.DataFrame(athlete_dict)
athlete_df

   name  age  height  weight team
0  John   20     180      70    A
1  Jane   21     170      65    B
2   Jim   22     185      80    A
3  Jill   23     175      75    B

#### Data Frames from Tuples

We can create the same data frame from a list of tuples (finite, ordered, and immutable sequence of elements).  Tuples are created using parentheses and here each tuple corresponds to a row of the data frame:

In [246]:
athlete_tuples = [
    ('John', 20, 180, 70, 'A'),
    ('Jane', 21, 170, 65, 'B'),
    ('Jim', 22, 185, 80, 'A'),
    ('Jill', 23, 175, 75, 'B')
]

We can again use the `data frame` function to convert this list of tuples into a data frame object, this time including the argument `columns` whose input is a list specifying the **column names** of the data frame:

In [247]:
athlete_df = pd.DataFrame(
    athlete_tuples, 
    columns=['name', 'age', 'height', 'weight', 'team']
    )
athlete_df

   name  age  height  weight team
0  John   20     180      70    A
1  Jane   21     170      65    B
2   Jim   22     185      80    A
3  Jill   23     175      75    B

### Attributes

Data frames have the following built-in attributes:

1. `.shape` - dimensions (number of rows and columns).
2. `.dtypes` - column data types (float, integer, object, etc.).
3. `.size` - first dimension (number of rows).
4. `.values` - an array of all data frame entries.
5. `.columns` - column index (column names).
6. `.index` - row index (row names).

We can obtain these attributes by appending the attribute name to the data frame name using the `.` syntax.  For example, here are the attributes for our `athlete_df`:

In [248]:
print(f"Shape: {athlete_df.shape}")
print(f"Data types: \n{athlete_df.dtypes}")
print(f"Size: {athlete_df.size}")
print(f"Values: \n{athlete_df.values}")

Shape: (4, 5)
Data types:
name      object
age        int64
height     int64
weight     int64
team      object
dtype: object
Size: 20
Values:
[['John' 20 180 70 'A']
 ['Jane' 21 170 65 'B']
 ['Jim' 22 185 80 'A']
 ['Jill' 23 175 75 'B']]

Recall these are f-strings, used to return strings whilst automatically converting data outputs.

### Indexing and Slicing

Index values are a way of referencing and retrieving specific values in multi-dimensional data structures.  Since data frames are always 2 dimensional, elements indexes have 2 values, for row and column, which are stored at the `.index` and `.columns` attributes respectively.  By default in data frames, rows are indexed by integers and columns by string labels:

In [249]:
print(f"Column index values: \n{athlete_df.columns}")
print(f"Row index values: \n{athlete_df.index}")

Column index values:
Index(['name', 'age', 'height', 'weight', 'team'], dtype='object')
Row index values:
RangeIndex(start=0, stop=4, step=1)

The elements of the data frame can be retrieved using **location** `.loc[ROW-INDEX, COL-INDEX]`.  Note the difference between `python` and `R` syntax.  If we would prefer to index elements numerically (i.e. row and column numbers) we can instead use `.iloc[ROW-POS]`:

In [250]:
print(athlete_df.loc[0, 'name'])
print(athlete_df.iloc[0, 0])

John
John

We can also use the `.index` and `.columns` attributes to change the values of the index, e.g. to set row names:

In [251]:
athlete_df.index = ['Athlete 1', 'Athlete 2', 'Athlete 3', 'Athlete 4']
athlete_df

           name  age  height  weight team
Athlete 1  John   20     180      70    A
Athlete 2  Jane   21     170      65    B
Athlete 3   Jim   22     185      80    A
Athlete 4  Jill   23     175      75    B

We can return entire columns / rows by **slicing**, that is using `:` to specify that we would like to have all of the values for that index.  We can also use `:` to specify certain ranges of values such as `a:b`:

In [252]:
athlete_df.loc[['Athlete 1', 'Athlete 2'], :]
athlete_df.iloc[1:3, :]

           name  age  height  weight team
Athlete 2  Jane   21     170      65    B
Athlete 3   Jim   22     185      80    A

We can take this futher and specify whole lists of index values that we would like to return, giving us complete control over that we index:

In [253]:
athlete_df.iloc[[1,3],[0,1,2,4]]

           name  age  height team
Athlete 2  Jane   21     170    B
Athlete 4  Jill   23     175    B

### Filtering

As with `numpy` we can **filter** data frames, that is, we can index values based on logical conditions:

In [254]:
athlete_df[athlete_df.team == "B"]

           name  age  height  weight team
Athlete 2  Jane   21     170      65    B
Athlete 4  Jill   23     175      75    B

A less efficient version uses `.loc` but this time we specify location using a boolean vector:

In [255]:
athlete_df.loc[athlete_df['age'] > 21, :]

           name  age  height  weight team
Athlete 3   Jim   22     185      80    A
Athlete 4  Jill   23     175      75    B

Below is a table of some of the most common symbols used to construct logical statements in python:

| Symbol | Usage | Meaning |
|:------:|-------|---------|
| `==` | `a == b` | Does a equal b? |
| `<=` | `a <= b` | Is a less than or equal to b? |
| `>=` | `a >= b` | Is a greater than or equal to b? |
| `<` | `a < b` | Is a less than b? |
| `>` | `a > b` | Is a greater than b? |
| `~` | `~p` | Returns negation of p |
| <code>&#124;</code> | `p | q` | p OR q |
| `&` | `p & q` | p AND q |
| `^` | `p ^ q` | p XOR q (exclusive or) |

In [256]:
athlete_df[(athlete_df.age > 21) & (athlete_df.team == "B")]

           name  age  height  weight team
Athlete 4  Jill   23     175      75    B

### Modifying Columns

We can add columns either by:

- Direct specification.
- Using `.loc` or `.iloc`.

With **direct specification** we can add a new column by simply assigning values to a new index `df['new_column_name']=[list_of_values]`:

In [257]:
athlete_df["country"] = ["UK", "France", "USA", "Australia"]
athlete_df

           name  age  height  weight team    country
Athlete 1  John   20     180      70    A         UK
Athlete 2  Jane   21     170      65    B     France
Athlete 3   Jim   22     185      80    A        USA
Athlete 4  Jill   23     175      75    B  Australia

We can also add new columns by specifying the position of the new column using either `.loc` or `.iloc` and specifying the values to be assigned to it:

In [258]:
athlete_df.iloc[:, 5] = ["USA", "USA", "USA", "USA"]
athlete_df

           name  age  height  weight team country
Athlete 1  John   20     180      70    A     USA
Athlete 2  Jane   21     170      65    B     USA
Athlete 3   Jim   22     185      80    A     USA
Athlete 4  Jill   23     175      75    B     USA

Notice here we have used **slicing** to specify that we are considering all the values for that index (i.e. all of the rows for that one column).

We can **remove rows and columns** by using `.drop` and specifying the arguments `index=...` or `columns=...` respectively:

In [259]:
athlete_df.drop(columns=['country'], index=['Athlete 3', 'Athlete 4'])

           name  age  height  weight team
Athlete 1  John   20     180      70    A
Athlete 2  Jane   21     170      65    B

<div class="alert alert-block alert-info">
<b>‼️ Problem 1:</b> 
</div>

You are given the following table of data below regarding the US Air Force aircraft specifications:

| Plane | Entered Service | Max Takeoff Weight (lbs) | Length (ft)     | Range (nmi)   | Ceiling (ft) |
|-------|-----------------|--------------------------|-----------------|---------------|--------------|
| F-22  | 2005            | 83,500                   | 62              | 410           | 65,000       |
| F-18   | 2001           | 66,000                   | 60              | 1.275         | 50,000       |
| F-16  | 1978            | 37,500                   | 47              | 1,260         | 50,000       |
| F-14  | 1974            | 74,350                   | 62              | 1,600         | 56,000       |
| A-10  | 1977            | 51,000                   | 53              | 290           | 45,000       |

1. Create a data frame of this data called `aircraft_df` using your preferred method.  In this case, make the plane's name the row index and ensure to use appropriate column names (using good principles: no spaces just - or _, no capitals).

In [260]:
# Solution 1.1
aircraft_df = pd.DataFrame({
    "Plane": ["F-22", "F-18", "F-16", "F-14", "A-10"],
    "Entered Service" : [2005, 2001, 1978, 1974, 1977],
    "Max Takeoff Weight (lbs)": [83500, 66000,37500,74350,51000],
    "Length (ft)" : [62, 60, 47, 62, 53],
    "Range (nmi)": [410, 1275, 1260, 1600, 290],
    "Ceiling (ft)": [65000, 50000, 50000, 56000, 45000]
    }
)
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft)
0,F-22,2005,83500,62,410,65000
1,F-18,2001,66000,60,1275,50000
2,F-16,1978,37500,47,1260,50000
3,F-14,1974,74350,62,1600,56000
4,A-10,1977,51000,53,290,45000

2. Return the 4th column using `.iloc` (remember `python` indexing starts at 0).

In [261]:
# Solution 1.2
aircraft_df.iloc[:, 3]
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft)
0,F-22,2005,83500,62,410,65000
1,F-18,2001,66000,60,1275,50000
2,F-16,1978,37500,47,1260,50000
3,F-14,1974,74350,62,1600,56000
4,A-10,1977,51000,53,290,45000

3. Return the "F-16" row using `.loc`.

In [262]:
# Solution 1.3
aircraft_df.loc[2]

Plane                        F-16
Entered Service              1978
Max Takeoff Weight (lbs)    37500
Length (ft)                    47
Range (nmi)                  1260
Ceiling (ft)                50000
Name: 2, dtype: object

4. Add a column called `Class` that specifies the aircraft class with the following value list `[fighter, fighter, fighter, fighter, attack]` (note the name letters?).

In [263]:
# Solution 1.4
aircraft_df["Class"] = ["fighter", "fighter","fighter","fighter","attack"]
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Class
0,F-22,2005,83500,62,410,65000,fighter
1,F-18,2001,66000,60,1275,50000,fighter
2,F-16,1978,37500,47,1260,50000,fighter
3,F-14,1974,74350,62,1600,56000,fighter
4,A-10,1977,51000,53,290,45000,attack

5. Add another column called `Long Range` that says `True` if the plane has a range over 1000 nmi and `False` otherwise.

In [264]:
# Solution 1.5
aircraft_df["Long Range"] = np.where(aircraft_df["Range (nmi)"] > 1000, True, False)
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Class,Long Range
0,F-22,2005,83500,62,410,65000,fighter,False
1,F-18,2001,66000,60,1275,50000,fighter,True
2,F-16,1978,37500,47,1260,50000,fighter,True
3,F-14,1974,74350,62,1600,56000,fighter,True
4,A-10,1977,51000,53,290,45000,attack,False

6. Create a new data frame called `long_range_fighters_df` that only contains fighters with a range over 1000 nmi.

In [265]:
# Solution 1.6
long_range_fighters_df = aircraft_df.loc[aircraft_df["Long Range"]]
long_range_fighters_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Class,Long Range
1,F-18,2001,66000,60,1275,50000,fighter,True
2,F-16,1978,37500,47,1260,50000,fighter,True
3,F-14,1974,74350,62,1600,56000,fighter,True

### Computations

Data frames have a lot of built-in syntax for performing operations.  For example, with numerical columns we can perform standard mathematical operations:

In [266]:
print(athlete_df['age'] + 10)
print(athlete_df['height'] * 3)

Athlete 1    30
Athlete 2    31
Athlete 3    32
Athlete 4    33
Name: age, dtype: int64
Athlete 1    540
Athlete 2    510
Athlete 3    555
Athlete 4    525
Name: height, dtype: int64

This is particularly useful when combined with redefining / creating new columns for changing the units of certain data (for example ft to m, miles to km).  For example, let's change athlete weight from kg to lbs:

In [267]:
athlete_df['weight_lbs'] = athlete_df['weight'] * 2.20462
athlete_df

           name  age  height  weight team country  weight_lbs
Athlete 1  John   20     180      70    A     USA    154.3234
Athlete 2  Jane   21     170      65    B     USA    143.3003
Athlete 3   Jim   22     185      80    A     USA    176.3696
Athlete 4  Jill   23     175      75    B     USA    165.3465

<div class="alert alert-block alert-info">
<b>‼️ Problem 2:</b> 
</div>

Modify the `aircraft_df` data base in the following ways:

1. Add a range column changing the units from nmi to km (1 nautical mile is 1.852 km).

In [268]:
# Solution 2.1
aircraft_df["Range (km)"] = aircraft_df["Range (nmi)"] * 1.852
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Class,Long Range,Range (km)
0,F-22,2005,83500,62,410,65000,fighter,False,759.32
1,F-18,2001,66000,60,1275,50000,fighter,True,2361.30
2,F-16,1978,37500,47,1260,50000,fighter,True,2333.52
3,F-14,1974,74350,62,1600,56000,fighter,True,2963.20
4,A-10,1977,51000,53,290,45000,attack,False,537.08

2. Add a length column changing the units from ft to m (1 meter is 3.28 ft).

In [269]:
# Solution 2.2
aircraft_df["Length (m)"] = aircraft_df["Length (ft)"] * 3.28
aircraft_df

,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Class,Long Range,Range (km),Length (m)
0,F-22,2005,83500,62,410,65000,fighter,False,759.32,203.36
1,F-18,2001,66000,60,1275,50000,fighter,True,2361.30,196.80
2,F-16,1978,37500,47,1260,50000,fighter,True,2333.52,154.16
3,F-14,1974,74350,62,1600,56000,fighter,True,2963.20,203.36
4,A-10,1977,51000,53,290,45000,attack,False,537.08,173.84

### Sorting

Often when we are preparing data we would like to **sort** the data frame into order using a specific column.  We can accomplish this using `.sort_values`.  We need to specify which column we would like to sort by with the `by=...` argument, then we can specify whether we would like the order to be `ascending=...` or not:

In [270]:
athlete_df.sort_values(by='weight', ascending=False)

           name  age  height  weight team country  weight_lbs
Athlete 3   Jim   22     185      80    A     USA    176.3696
Athlete 4  Jill   23     175      75    B     USA    165.3465
Athlete 1  John   20     180      70    A     USA    154.3234
Athlete 2  Jane   21     170      65    B     USA    143.3003

We can specify multiple values to sort by including lists in our arguments:

In [271]:
athlete_df.sort_values(by=['team', 'age'], ascending=[True, True])

           name  age  height  weight team country  weight_lbs
Athlete 1  John   20     180      70    A     USA    154.3234
Athlete 3   Jim   22     185      80    A     USA    176.3696
Athlete 2  Jane   21     170      65    B     USA    143.3003
Athlete 4  Jill   23     175      75    B     USA    165.3465


### Grouping and Aggregation

Grouping and aggregation are useful in generating data summaries, which are often important starting points in exploring a dataset.

**Aggregation** literally means 'putting together' (etymologically the word means 'joining the herd') -- in statistics and data science, this refers to data summaries like an average, a minimum, or a measure of spread such as the sample variance or mean absolute deviation (data herding!). From a technical point of view, operations that take multiple values as inputs and return a single output are considered summaries -- in other words, statistics. Some of the most common aggregations are:

* sum
* product
* count
* number of distinct values
* mean
* median
* variance
* standard deviation
* minimum/maximum
* quantiles

Pandas has built-in data frame operations that compute most of these summaries across either axis (column-wise or row-wise):

* `.sum()`
* `.prod()`
* `.mean()`
* `.median()`
* `.var()`
* `.std()`
* `.nunique()`
* `.min()` and `.max()`
* `.quantile()`

To illustrate these operations, let's consider a larger data set.  We use `head()` to view the first few rows:

In [272]:
baby_names = pd.read_csv('data/baby_names.csv')
print(f"Shape: {baby_names.shape}")
baby_names.head()

Shape: (190762, 5)

  State Sex  Year       Name  Count
0    CA   F  1990    Jessica   6635
1    CA   F  1990     Ashley   4537
2    CA   F  1990  Stephanie   4001
3    CA   F  1990     Amanda   3856
4    CA   F  1990   Jennifer   3611

We see that this is a very large data set with records of counts of names per year for each state.  To demonstrate some of these aggregations first isolate data from 1995.

In [273]:
baby_names_1995 = baby_names[baby_names['Year'] == 1995]
baby_names_1995.head()

      State Sex  Year       Name  Count
18604    CA   F  1995    Jessica   4620
18605    CA   F  1995     Ashley   2903
18606    CA   F  1995  Stephanie   2858
18607    CA   F  1995   Jennifer   2697
18608    CA   F  1995   Samantha   2425

How many individuals were counted in total in 1995? We can address that by computing a sum of the counts:

In [274]:
# n for 1995
print(baby_names_1995.Count.sum())

494580

What is the typical frequency of all names in 1995? We can address that by computing the average count:

In [275]:
# average count for a name in 1995
print(baby_names_1995.Count.mean())

81.18516086671043

Suppose we would like to find the most common male baby name in 1995.  If we try to apply the maximum we run into a problem.  The output returns the maximum (alphabetically in some cases) of all columns!

In [276]:
baby_names_1995.max()

State        CA
Sex           M
Year       1995
Name     Zyanya
Count      5003
dtype: object

We overcome this problem using **grouping**.  In general, any variable in a data frame can be used to define a grouping structure on the rows (or, less common, columns). After grouping, any data frame operations will be executed within each group, but not across groups. This can be used to generate grouped summaries, such as the maximum count for boys and girls; as a point of terminology, we'd describe this summary as 'maximum count by sex' (SUMMARY by GROUPING VARIABLE).

The `.groupby()` function defines such a structure; here is the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.data frame.groupby.html). The cell below groups the `names_95` data frame by sex. Notice that when the grouped data frame is previewed with `.head()`, the first few rows are returned *for each group*.

In [277]:
baby_names_1995_bysex = baby_names_1995.groupby('Sex')
baby_names_1995_bysex.head()

       State Sex  Year         Name  Count
18604     CA   F  1995      Jessica   4620
18605     CA   F  1995       Ashley   2903
18606     CA   F  1995    Stephanie   2858
18607     CA   F  1995     Jennifer   2697
18608     CA   F  1995     Samantha   2425
124938    CA   M  1995       Daniel   5003
124939    CA   M  1995      Michael   4783
124940    CA   M  1995         Jose   4571
124941    CA   M  1995  Christopher   4098
124942    CA   M  1995        David   4030

Now any aggregation operations applied to the grouped data frame will be applied separately to the rows where `Sex == M` and the rows where `Sex == F`. For example, computing `.sum()` on the grouped data frame will show the total number of individuals in the data for 1995 *by sex*:

In [278]:
# number of individuals by sex
baby_names_1995_bysex.Count.sum()

Sex
F    234552
M    260028
Name: Count, dtype: int64

The most frequent boy and girl names can be found using `.idxmax()` groupwise to obtain the index of the first occurrence of the maximum count for each sex, and then slicing with `.loc`:

In [279]:
# first most common names by sex
baby_names_1995.loc[baby_names_1995_bysex.Count.idxmax(), :]

       State Sex  Year     Name  Count
18604     CA   F  1995  Jessica   4620
124938    CA   M  1995   Daniel   5003

This is an example of chaining operations (i.e. we have first applied `Count` and then `idxmax`).  This is similar to piping in `R` and allows us to apply multiple functions one after the other on the same line of code.  In reality, we did not even need to make a new data set, we can also perform the filtering in line:

In [280]:
baby_names[baby_names.Year == 1995].groupby('Sex').Count.sum()

Sex
F    234552
M    260028
Name: Count, dtype: int64

Chains can get somewhat long, but they have the advantage of making codes more efficient, and often more readable. We did above in one step what took several lines before. Further, this chain can almost be read aloud:

"Take baby names, filter on year, *then* group by sex, *then* select name counts, *then* compute the sum."

Let's now consider computing the average counts of boy and girl names for each year 1990-1995. This can be accomplished by the following chain (notice it is possible to group by multiple variables).

In [281]:
# average counts by sex and year
baby_names[baby_names.Year <= 1995].groupby(['Year', 'Sex'])['Count'].mean()

Year  Sex
1990  F       70.085760
      M      115.231930
1991  F       70.380888
      M      114.608124
1992  F       68.744510
      M      110.601556
1993  F       66.330675
      M      107.896552
1994  F       66.426301
      M      102.967966
1995  F       64.900941
      M      104.934625
Name: Count, dtype: float64

This display is not ideal. We can 'pivot' the table into a wide format by adding a few extra steps in the chain: change the indices to columns; then define a new shape by specifying which column should be the new row index, which should be the new column index, and which values should populate the table.

In [282]:
# average counts by sex and year
baby_names[baby_names.Year <= 1995].groupby(['Year', 'Sex'])['Count'].mean().reset_index().pivot(index = 'Sex', columns = 'Year', values = 'Count')

Year       1990        1991        1992        1993        1994        1995
Sex
F      70.08576   70.380888   68.744510   66.330675   66.426301   64.900941
M     115.23193  114.608124  110.601556  107.896552  102.967966  104.934625

**Style comment: break long chains over multiple lines with indentation.** The above chain is too long to be readable. To balance the readability of codes with the efficiency of chaining, it is good practice to break long chains over several lines, with appropriate indentations. Here is a better-styled version of the previous cell:

In [283]:
# better style
baby_names[baby_names.Year <= 1995].groupby(
    ['Year', 'Sex']
    )['Count'].mean(
    ).reset_index(
    ).pivot(
        index = 'Sex', 
        columns = 'Year', 
        values = 'Count'
    )

Year       1990        1991        1992        1993        1994        1995
Sex
F      70.08576   70.380888   68.744510   66.330675   66.426301   64.900941
M     115.23193  114.608124  110.601556  107.896552  102.967966  104.934625

Here are some rules of thumb on style.

* Separate comparisons by spaces (`a<b` as `a < b`)
* Split chains longer than 30-40 characters over multiple lines
* Split lines between delimiters `(`, `)`
* Increase indentation for lines between delimiters
* For chained operations, try to get each step in the chain shown on a separate line
* For functions with multiple arguments, split lines so that each argument is on its own line

<div class="alert alert-block alert-info">
<b>‼️ Problem 3:</b> 
</div>

Write a chain with appropriate style to display the (first) most common boy and girl names in each of the years 2005-2015. Do this in two steps:

1. First filter `baby_names` by year, then group by year and sex, and then find the indices of the first occurrences of the largest counts. Store these indices as `ind`.
2. Then use `.loc[]` with your stored indices to slice `baby_names` so as to retrieve the rows corresponding to each most frequent name each year and for each sex; then pivot this table so that the columns are years, the rows are sexes, and the entries are names.

In [284]:
# Solution 3.1
baby_names_2005 = baby_names[(baby_names['Year'] >= 2005) & (baby_names['Year'] <= 2015)]

ind = baby_names_2005.groupby(
    ['Year', 'Sex']
)['Count'].idxmax()

ind

Year  Sex
2005  F       55767
      M      150164
2006  F       59866
      M      152939
2007  F       64073
      M      155807
2008  F       68355
      M      158775
2009  F       72602
      M      161686
2010  F       76793
      M      164614
2011  F       80890
      M      167527
2012  F       84883
      M      170414
2013  F       88981
      M      173323
2014  F       92944
      M      176221
2015  F       96958
      M      179159
Name: Count, dtype: int64

In [285]:
# Solution 3.2
baby_names_2005.loc[ind, :].pivot(
    columns='Year',
    index='Sex',
    values='Name'
)

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Sex,,,,,,,,,,,
F,Emily,Emily,Emily,Isabella,Isabella,Isabella,Sophia,Sophia,Sophia,Sophia,Sophia
M,Daniel,Daniel,Daniel,Daniel,Daniel,Jacob,Jacob,Jacob,Jacob,Noah,Noah

### Merging

In real data work, information about the same “thing” is often split across multiple tables. Pandas supports SQL-style joins using `pd.merge`.

**Key ideas (read before starting Problem 3):**

- A **key** is a column (or set of columns) that identifies which rows “match” across tables.
- The most common syntax is:

`pd.merge(left_df, right_df, on='key_column', how='left')`

- `how=` controls which rows are kept:
    - `inner`: only matching keys in *both* tables
    - `left`: keep all rows from the left table, match what you can from the right
    - `right`: keep all rows from the right table
    - `outer`: keep all rows from both (fills missing values with `NaN`)

**Helpful tips:**

- If the key column names differ, use `left_on=...` and `right_on=...`.
- If both tables share non-key column names, use `suffixes=('_left', '_right')`.
- A good sanity check is to compare the number of rows before/after the merge and to inspect a few merged rows with `.head()`.

<div class="alert alert-block alert-info">
<b>‼️ Problem 4:</b>
</div>

In Problem 1 you created `aircraft_df` and added a `class` column (and `long_range`). In this problem you’ll create a small “lookup table” and **merge** it into `aircraft_df`.

1. Create a new dataframe called `mission_lookup_df` with columns:
    - `class`
    - `mission_type`

   Use the mapping:
    - `fighter` → `air_defense`
    - `attack` → `strike`

2. Merge `mission_lookup_df` into `aircraft_df` on the `class` column. Store the merged result as `aircraft_with_mission_df`.

3. Create `long_range_missions_df` by filtering `aircraft_with_mission_df` to only rows with `long_range == True`.

4. Create `mission_summary_df` as a grouped summary **by** `mission_type` that computes:
    - average (mean) max takeoff weight (lbs)
    - median length

   Then sort this summary by mean weight descending.

**Hints:**

- Step 2 should be a single call to `pd.merge(...)`.
- Use `.groupby('mission_type')` followed by an aggregation method such as `.agg(...)`.
- Your exact column names for weight/length depend on what you chose in Problem 1—use the corresponding columns you created there.

In [286]:
# Solution 4.1 (build the lookup table)
mission_lookup_df = pd.DataFrame({
    'Class': ['fighter', 'attack'],
    'mission_type': ['air_defense', 'strike']})
mission_lookup_df

     Class mission_type
0  fighter  air_defense
1   attack       strike

In [287]:
# Solution 4.2 (merge)
aircraft_with_mission_df =  pd.merge(mission_lookup_df, aircraft_df, on="Class", how="left")
aircraft_with_mission_df

,Class,mission_type,Plane,Entered Service,Max Takeoff Weight (lbs),Length (ft),Range (nmi),Ceiling (ft),Long Range,Range (km),Length (m)
0,fighter,air_defense,F-22,2005,83500,62,410,65000,False,759.32,203.36
1,fighter,air_defense,F-18,2001,66000,60,1275,50000,True,2361.30,196.80
2,fighter,air_defense,F-16,1978,37500,47,1260,50000,True,2333.52,154.16
3,fighter,air_defense,F-14,1974,74350,62,1600,56000,True,2963.20,203.36
4,attack,strike,A-10,1977,51000,53,290,45000,False,537.08,173.84

In [288]:
# Solution 4.3–4.4 (filter + summary)
long_range_missions_df = aircraft_with_mission_df[aircraft_with_mission_df['Long Range'] == True]
print(long_range_missions_df)


mission_summary_df = aircraft_with_mission_df.groupby('mission_type').agg(
    mean_max_takeoff_weight_lbs=('Max Takeoff Weight (lbs)', 'mean'),
    median_length=('Length (ft)', 'median')
).reset_index()

mission_summary_df.head()

     Class mission_type Plane  Entered Service  Max Takeoff Weight (lbs)  \
1  fighter  air_defense  F-18             2001                     66000
2  fighter  air_defense  F-16             1978                     37500
3  fighter  air_defense  F-14             1974                     74350

   Length (ft)  Range (nmi)  Ceiling (ft)  Long Range  Range (km)  Length (m)
1           60         1275         50000        True     2361.30      196.80
2           47         1260         50000        True     2333.52      154.16
3           62         1600         56000        True     2963.20      203.36

  mission_type  mean_max_takeoff_weight_lbs  median_length
0  air_defense                      65337.5           61.0
1       strike                      51000.0           53.0

### Reshaping

You’ve already seen how to make a “wide” table using `pivot(...)`. Another common reshape is **wide → long**, which is usually done with `.melt(...)`.

**When to use what:**

- `pivot(index=..., columns=..., values=...)`: long → wide (creates a spreadsheet-like table)
- `reset_index()`: turns index levels back into ordinary columns
- `melt(...)`: wide → long (creates one row per combination of identifiers)

A typical workflow is:

1. Compute a summary in long format
2. Pivot it to wide format for readability
3. (Optionally) melt it back to long format for plotting/modeling

<div class="alert alert-block alert-info">
<b>‼️ Problem 5:</b>
</div>

In this problem you’ll practice summarizing, pivoting, and melting using the `baby_names` dataset in `data/baby_names.csv`.

1. Load the dataset as `baby_names`.
2. Filter to years 1990–1995 (inclusive) and store as `baby_90_95`.
3. Compute the **mean** `Count` for each (`Year`, `Sex`) pair and store as `avg_counts_long_df`.
4. Pivot to wide format so that:
    - rows are `Year`
    - columns are `Sex`
    - values are the mean counts
   Store as `avg_counts_wide_df`.
5. Melt `avg_counts_wide_df` back to long format and store as `avg_counts_long_again_df`.

**Partial check (recommended):** after melting, sort both long tables by `Year` then `Sex` and compare the values.

**Hints:**

- Step 3: start with `baby_90_95.groupby(['Year','Sex'])['Count'].mean()`.
- You’ll likely need `.reset_index()` before pivoting.
- For melting, you may want to do `avg_counts_wide_df.reset_index().melt(id_vars='Year', var_name='Sex', value_name='Count_mean')` (adjust names as needed).

In [289]:
# Solution 5.1–5.2 (load + filter)

# TODO: filter to years 1990–1995 inclusive
baby_90_95 = baby_names[(baby_names['Year'] >= 1990) & (baby_names['Year'] <= 1995)].copy()

baby_90_95.head()

  State Sex  Year       Name  Count
0    CA   F  1990    Jessica   6635
1    CA   F  1990     Ashley   4537
2    CA   F  1990  Stephanie   4001
3    CA   F  1990     Amanda   3856
4    CA   F  1990   Jennifer   3611

In [290]:
# Solution 5.3 (mean count by Year and Sex, long format)

# TODO: compute mean Count by Year and Sex
avg_counts_long_df = baby_90_95.groupby(['Year', 'Sex'])['Count'].mean().reset_index()

avg_counts_long_df.head()

   Year Sex       Count
0  1990   F   70.085760
1  1990   M  115.231930
2  1991   F   70.380888
3  1991   M  114.608124
4  1992   F   68.744510

In [291]:
# Solution 5.4 (pivot to wide)

# TODO: pivot so rows are Year, columns are Sex, values are mean Count
avg_counts_wide_df = avg_counts_long_df.pivot(index='Year', columns='Sex', values='Count')

avg_counts_wide_df

Sex           F           M
Year
1990  70.085760  115.231930
1991  70.380888  114.608124
1992  68.744510  110.601556
1993  66.330675  107.896552
1994  66.426301  102.967966
1995  64.900941  104.934625

In [292]:
# Solution 5.5 (melt back to long) + partial check

# TODO: melt wide back to long
avg_counts_long_again_df = avg_counts_wide_df.reset_index().melt(
    id_vars='Year',
    var_name='Sex',
    value_name='Count'
)

# Recommended check: compare sorted tables
a = avg_counts_long_df.sort_values(['Year','Sex']).reset_index(drop=True)
b = avg_counts_long_again_df.sort_values(['Year','Sex']).reset_index(drop=True)
print(a.head())
print(b.head())

avg_counts_long_again_df.head()

   Year Sex       Count
0  1990   F   70.085760
1  1990   M  115.231930
2  1991   F   70.380888
3  1991   M  114.608124
4  1992   F   68.744510
   Year Sex       Count
0  1990   F   70.085760
1  1990   M  115.231930
2  1991   F   70.380888
3  1991   M  114.608124
4  1992   F   68.744510

   Year Sex      Count
0  1990   F  70.085760
1  1991   F  70.380888
2  1992   F  68.744510
3  1993   F  66.330675
4  1994   F  66.426301

---

## Submission Checklist

- Ensure you have completed all problems in the notebook.
- Clear your document code outputs and rerun the notebook, checking for any new errors.
- At the top of your notebook click more options -> export -> pdf.
- Make sure your pdf has all code chunks clearly visible and executed.
- Submit before the posted deadline.